//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFAuthConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uporabniki
    {
        public long UporabnikKLJ { get; set; }
        public string UporabnikID { get; set; }
        public string Ime { get; set; }
        public string Priimek { get; set; }
        public string WinUsername { get; set; }
        public string RFID { get; set; }
    }
}
