//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCRU.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CruDBEntities : DbContext
    {
        public CruDBEntities()
            : base("name=CruDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aplikacija> Aplikacija { get; set; }
        public virtual DbSet<Lokacija> Lokacija { get; set; }
        public virtual DbSet<Pravice> Pravice { get; set; }
        public virtual DbSet<Uporabniki> Uporabniki { get; set; }
        public virtual DbSet<Vloge> Vloge { get; set; }
        public virtual DbSet<VlogeUporabnikov> VlogeUporabnikov { get; set; }
    }
}
