//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace si.hit.WebCRU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vloge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vloge()
        {
            this.VlogeUporabnikov = new HashSet<VlogeUporabnikov>();
            this.Pravice = new HashSet<Pravice>();
        }
    
        public long VlogaKLJ { get; set; }
        public long AplikacijaKLJ { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
    
        public virtual Aplikacija Aplikacija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VlogeUporabnikov> VlogeUporabnikov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pravice> Pravice { get; set; }
    }
}
