//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCRU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vloge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vloge()
        {
            this.VlogePravice = new HashSet<VlogePravice>();
        }
    
        public long VlogaKLJ { get; set; }
        public Nullable<long> AplikacijaKLJ { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VlogePravice> VlogePravice { get; set; }
    }
}
