//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplikacija
    {
        public long AplikacijaKLJ { get; set; }
        public string Ime { get; set; }
        public string Naziv { get; set; }
        public string Http { get; set; }
        public string Opis { get; set; }
        public string Database { get; set; }
    }
}
